import './globals.css';
import type { Metadata } from 'next';
import { Inter, Ubuntu } from 'next/font/google';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
const ubuntu = Ubuntu({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-ubuntu',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${ubuntu.variable} `}>
        {children}
      </body>
    </html>
  );
}
